#!/usr/bin/env python3
"""
Script per pinnare le versioni dei requirements e separare dev da prod
Uso: python scripts/pin_requirements.py
"""
import subprocess
import sys
import os

def run_command(cmd, cwd=None):
    """Esegue un comando e restituisce l'output"""
    try:
        result = subprocess.run(
            cmd, 
            shell=True, 
            capture_output=True, 
            text=True, 
            cwd=cwd
        )
        if result.returncode != 0:
            print(f"❌ Errore eseguendo: {cmd}")
            print(f"Stderr: {result.stderr}")
            return None
        return result.stdout.strip()
    except Exception as e:
        print(f"❌ Errore: {e}")
        return None

def main():
    print("🔧 Pinning requirements per produzione...")
    
    # Assicurati di essere nella directory backend
    if not os.path.exists("requirements.txt"):
        print("❌ Esegui questo script dalla directory backend/")
        sys.exit(1)
    
    # Attiva l'ambiente virtuale se esiste
    venv_activate = None
    if os.path.exists("../venv/bin/activate"):
        venv_activate = "source ../venv/bin/activate && "
    elif os.path.exists("venv/bin/activate"):
        venv_activate = "source venv/bin/activate && "
    
    # Pinnare requirements.txt (solo runtime)
    print("📦 Pinnando requirements.txt per produzione...")
    cmd = f"{venv_activate or ''}pip freeze"
    output = run_command(cmd)
    
    if not output:
        print("❌ Impossibile ottenere le dipendenze installate")
        sys.exit(1)
    
    # Filtra solo le dipendenze runtime (esclude dev tools)
    runtime_packages = []
    dev_packages = []
    
    for line in output.split('\n'):
        if line and '==' in line:
            package = line.split('==')[0].lower()
            
            # Lista dei pacchetti di sviluppo
            dev_keywords = [
                'pytest', 'black', 'flake8', 'isort', 'mypy', 'ipython', 
                'jupyter', 'pre-commit', 'ipdb', 'debugpy', 'sphinx', 
                'python-dotenv', 'watchdog', 'coverage'
            ]
            
            if any(keyword in package for keyword in dev_keywords):
                dev_packages.append(line)
            else:
                runtime_packages.append(line)
    
    # Salva requirements.txt (solo runtime)
    with open("requirements.txt", "w") as f:
        f.write("# Production requirements - runtime only\n")
        f.write("# Generated by pin_requirements.py\n\n")
        for package in sorted(runtime_packages):
            f.write(f"{package}\n")
    
    # Salva dev-requirements.txt
    with open("dev-requirements.txt", "w") as f:
        f.write("# Development requirements - NON installare in produzione\n")
        f.write("# Generated by pin_requirements.py\n\n")
        for package in sorted(dev_packages):
            f.write(f"{package}\n")
    
    print(f"✅ Requirements.txt aggiornato con {len(runtime_packages)} pacchetti runtime")
    print(f"✅ Dev-requirements.txt creato con {len(dev_packages)} pacchetti dev")
    print("\n💡 Per installare le dipendenze di sviluppo:")
    print("   pip install -r dev-requirements.txt")
    print("\n💡 Per installare solo le dipendenze di produzione:")
    print("   pip install -r requirements.txt")

if __name__ == "__main__":
    main()
