"""Gamma calls storage

Revision ID: 0015
Revises: 0014
Create Date: 2025-08-26 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '0015_gamma_calls_storage'
down_revision = '0014_kb_structured_cards_and_quality'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create call_records table
    op.create_table('call_records',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('workspace_id', sa.String(), nullable=False),
        sa.Column('campaign_id', sa.String(), nullable=True),
        sa.Column('agent_id', sa.String(), nullable=True),
        sa.Column('number_id', sa.String(), nullable=True),
        sa.Column('retell_call_id', sa.String(), nullable=True),
        sa.Column('started_at', sa.DateTime(), nullable=False),
        sa.Column('ended_at', sa.DateTime(), nullable=True),
        sa.Column('duration_sec', sa.Integer(), nullable=True),
        sa.Column('direction', sa.String(), nullable=True),
        sa.Column('country_iso', sa.String(length=2), nullable=True),
        sa.Column('language', sa.String(), nullable=True),
        sa.Column('outcome', sa.String(), nullable=True),
        sa.Column('outcome_reason', sa.String(), nullable=True),
        sa.Column('cost_cents', sa.Integer(), nullable=True),
        sa.Column('recording_url', sa.String(), nullable=True),
        sa.Column('transcript_sha', sa.String(length=64), nullable=True),
        sa.Column('phone_hash', sa.String(length=64), nullable=True),
        sa.Column('meta_json', sqlite.JSON, nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
        sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create call_turns table
    op.create_table('call_turns',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('call_id', sa.String(), nullable=False),
        sa.Column('speaker', sa.String(), nullable=False),
        sa.Column('t_start_ms', sa.Integer(), nullable=False),
        sa.Column('t_end_ms', sa.Integer(), nullable=False),
        sa.Column('text', sa.Text(), nullable=False),
        sa.Column('sentiment', sa.Float(), nullable=True),
        sa.Column('confidence', sa.Float(), nullable=True),
        sa.Column('meta_json', sqlite.JSON, nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['call_id'], ['call_records.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create call_quality table
    op.create_table('call_quality',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('call_id', sa.String(), nullable=False),
        sa.Column('talk_time_agent_sec', sa.Integer(), nullable=True),
        sa.Column('talk_time_customer_sec', sa.Integer(), nullable=True),
        sa.Column('dead_air_sec', sa.Integer(), nullable=True),
        sa.Column('interruptions_agent', sa.Integer(), nullable=True),
        sa.Column('interruptions_customer', sa.Integer(), nullable=True),
        sa.Column('sentiment_avg', sa.Float(), nullable=True),
        sa.Column('sentiment_agent', sa.Float(), nullable=True),
        sa.Column('sentiment_customer', sa.Float(), nullable=True),
        sa.Column('objections_json', sqlite.JSON, nullable=True),
        sa.Column('analysis_model', sa.String(), nullable=True),
        sa.Column('analysis_tokens', sa.Integer(), nullable=True),
        sa.Column('analysis_cost_micros', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['call_id'], ['call_records.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create call_daily_aggregates table
    op.create_table('call_daily_aggregates',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('workspace_id', sa.String(), nullable=False),
        sa.Column('date', sa.DateTime(), nullable=False),
        sa.Column('campaign_id', sa.String(), nullable=True),
        sa.Column('agent_id', sa.String(), nullable=True),
        sa.Column('country_iso', sa.String(length=2), nullable=True),
        sa.Column('language', sa.String(), nullable=True),
        sa.Column('reached', sa.Integer(), nullable=True),
        sa.Column('connected', sa.Integer(), nullable=True),
        sa.Column('qualified', sa.Integer(), nullable=True),
        sa.Column('booked', sa.Integer(), nullable=True),
        sa.Column('total_duration_sec', sa.Integer(), nullable=True),
        sa.Column('avg_duration_sec', sa.Float(), nullable=True),
        sa.Column('total_cost_cents', sa.Integer(), nullable=True),
        sa.Column('avg_cost_cents', sa.Float(), nullable=True),
        sa.Column('avg_sentiment', sa.Float(), nullable=True),
        sa.Column('total_objections', sa.Integer(), nullable=True),
        sa.Column('last_updated', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
        sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create call_webhook_events table
    op.create_table('call_webhook_events',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('workspace_id', sa.String(), nullable=False),
        sa.Column('event_id', sa.String(), nullable=False),
        sa.Column('event_type', sa.String(), nullable=False),
        sa.Column('payload_json', sqlite.JSON, nullable=False),
        sa.Column('processed', sa.Boolean(), nullable=True),
        sa.Column('processed_at', sa.DateTime(), nullable=True),
        sa.Column('error_details', sqlite.JSON, nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create ai_objection_cache table
    op.create_table('ai_objection_cache',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('workspace_id', sa.String(), nullable=False),
        sa.Column('snippet_sha', sa.String(length=64), nullable=False),
        sa.Column('label', sa.String(), nullable=False),
        sa.Column('confidence', sa.Float(), nullable=True),
        sa.Column('model_used', sa.String(), nullable=True),
        sa.Column('tokens_used', sa.Integer(), nullable=True),
        sa.Column('cost_micros', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('last_accessed', sa.DateTime(), nullable=True),
        sa.Column('access_count', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create indexes for performance
    op.create_index('ix_call_records_workspace_id', 'call_records', ['workspace_id'], unique=False)
    op.create_index('ix_call_records_campaign_id', 'call_records', ['campaign_id'], unique=False)
    op.create_index('ix_call_records_agent_id', 'call_records', ['agent_id'], unique=False)
    op.create_index('ix_call_records_started_at', 'call_records', ['started_at'], unique=False)
    op.create_index('ix_call_records_outcome', 'call_records', ['outcome'], unique=False)
    op.create_index('ix_call_records_country_iso', 'call_records', ['country_iso'], unique=False)
    op.create_index('ix_call_records_language', 'call_records', ['language'], unique=False)
    
    op.create_index('ix_call_turns_call_id', 'call_turns', ['call_id'], unique=False)
    op.create_index('ix_call_turns_speaker', 'call_turns', ['speaker'], unique=False)
    
    op.create_index('ix_call_quality_call_id', 'call_quality', ['call_id'], unique=False)
    
    op.create_index('ix_call_daily_aggregates_workspace_date', 'call_daily_aggregates', ['workspace_id', 'date'], unique=False)
    op.create_index('ix_call_daily_aggregates_campaign_date', 'call_daily_aggregates', ['campaign_id', 'date'], unique=False)
    op.create_index('ix_call_daily_aggregates_agent_date', 'call_daily_aggregates', ['agent_id', 'date'], unique=False)
    op.create_index('ix_call_daily_aggregates_country_iso', 'call_daily_aggregates', ['country_iso'], unique=False)
    op.create_index('ix_call_daily_aggregates_language', 'call_daily_aggregates', ['language'], unique=False)
    
    op.create_index('ix_call_webhook_events_event_id', 'call_webhook_events', ['event_id'], unique=True)
    op.create_index('ix_call_webhook_events_workspace_id', 'call_webhook_events', ['workspace_id'], unique=False)
    op.create_index('ix_call_webhook_events_event_type', 'call_webhook_events', ['event_type'], unique=False)
    
    op.create_index('ix_ai_objection_cache_snippet_sha', 'ai_objection_cache', ['snippet_sha'], unique=True)
    op.create_index('ix_ai_objection_cache_workspace_id', 'ai_objection_cache', ['workspace_id'], unique=False)
    op.create_index('ix_ai_objection_cache_label', 'ai_objection_cache', ['label'], unique=False)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop indexes
    op.drop_index('ix_ai_objection_cache_label', table_name='ai_objection_cache')
    op.drop_index('ix_ai_objection_cache_workspace_id', table_name='ai_objection_cache')
    op.drop_index('ix_ai_objection_cache_snippet_sha', table_name='ai_objection_cache')
    
    op.drop_index('ix_call_webhook_events_event_type', table_name='call_webhook_events')
    op.drop_index('ix_call_webhook_events_workspace_id', table_name='call_webhook_events')
    op.drop_index('ix_call_webhook_events_event_id', table_name='call_webhook_events')
    
    op.drop_index('ix_call_daily_aggregates_language', table_name='call_daily_aggregates')
    op.drop_index('ix_call_daily_aggregates_country_iso', table_name='call_daily_aggregates')
    op.drop_index('ix_call_daily_aggregates_agent_date', table_name='call_daily_aggregates')
    op.drop_index('ix_call_daily_aggregates_campaign_date', table_name='call_daily_aggregates')
    op.drop_index('ix_call_daily_aggregates_workspace_date', table_name='call_daily_aggregates')
    
    op.drop_index('ix_call_quality_call_id', table_name='call_quality')
    
    op.drop_index('ix_call_turns_speaker', table_name='call_turns')
    op.drop_index('ix_call_turns_call_id', table_name='call_turns')
    
    op.drop_index('ix_call_records_language', table_name='call_records')
    op.drop_index('ix_call_records_country_iso', table_name='call_records')
    op.drop_index('ix_call_records_outcome', table_name='call_records')
    op.drop_index('ix_call_records_started_at', table_name='call_records')
    op.drop_index('ix_call_records_agent_id', table_name='call_records')
    op.drop_index('ix_call_records_campaign_id', table_name='call_records')
    op.drop_index('ix_call_records_workspace_id', table_name='call_records')
    
    # Drop tables
    op.drop_table('ai_objection_cache')
    op.drop_table('call_webhook_events')
    op.drop_table('call_daily_aggregates')
    op.drop_table('call_quality')
    op.drop_table('call_turns')
    op.drop_table('call_records')
    
    # ### end Alembic commands ###
