export const LANG_OPTIONS = [
  { locale: 'en-US', code: 'EN', label: 'English' },
  { locale: 'it-IT', code: 'IT', label: 'Italiano' },
  { locale: 'fr-FR', code: 'FR', label: 'Français' },
  { locale: 'ar-EG', code: 'AR', label: 'العربية' },
  { locale: 'hi-IN', code: 'HI', label: 'हिन्दी' },
]

export function displayLang(locale) {
  const found = LANG_OPTIONS.find((l) => l.locale === locale)
  if (!found) return locale
  return `${found.label} (${found.code})`
}

// i18n keys for Import Wizard
export const IMPORT_KEYS = {
  'en-US': {
    'pages.import.upload.title': 'Import Contacts',
    'pages.import.upload.subtitle': 'Upload a CSV file or paste data to import contacts',
    'pages.import.upload.drag_drop': 'Drag & drop a CSV file here',
    'pages.import.upload.drop_here': 'Drop the file here',
    'pages.import.upload.or_click': 'or click to browse',
    'pages.import.upload.supported_formats': 'Supports CSV, XLS, XLSX (max 50MB)',
    'pages.import.paste.label': 'Paste CSV data',
    'pages.import.paste.placeholder': 'Paste your CSV data here (with headers)...',
    'pages.import.paste.processing': 'Processing...',
    'pages.import.paste.process': 'Process Data',
    'pages.import.sheet.title': 'Google Sheets Integration',
    'pages.import.sheet.subtitle': 'Coming soon! You can export your Google Sheet as CSV and upload it here.',
    'pages.import.sheet.upload_csv': 'Upload CSV Instead',
    'pages.import.processing': 'Processing your data...',
    'pages.import.preview.title': 'Data Preview',
    'pages.import.preview.rows': 'Rows',
    'pages.import.preview.fields': 'Fields',
    'pages.import.preview.delimiter': 'Delimiter',
    'pages.import.preview.continue': 'Continue to Mapping',
    'pages.import.preview.showing': 'Showing first 5 rows of',
    'pages.import.preview.total': 'total rows',
    'pages.import.mapping.title': 'Field Mapping & Rules',
    'pages.import.mapping.subtitle': 'Map CSV columns to contact fields and configure import rules',
    'pages.import.mapping.fields': 'Field Mapping',
    'pages.import.prefix.title': 'Phone Number Prefix Configuration',
    'pages.import.prefix.strategy': 'Prefix Strategy',
    'pages.import.prefix.auto': 'Auto-detect (+39, 0039, none)',
    'pages.import.prefix.force_39': 'Force +39 prefix',
    'pages.import.prefix.force_0039': 'Force 0039 prefix',
    'pages.import.prefix.no_prefix': 'No prefix (keep as-is)',
    'pages.import.prefix.default_country': 'Default Country',
    'pages.import.prefix.apply_to_all': 'Apply prefix rules to all phone numbers',
    'pages.import.dedupe.title': 'Deduplication Rules',
    'pages.import.dedupe.check_on': 'Check for duplicates on:',
    'pages.import.dedupe.resolve_strategy': 'When duplicates found:',
    'pages.import.dedupe.skip': 'Skip duplicates',
    'pages.import.dedupe.merge': 'Merge and update existing',
    'pages.import.review.title': 'Review & Launch',
    'pages.import.review.subtitle': 'Review your import configuration and launch the job',
    'pages.import.review.summary': 'Import Summary',
    'pages.import.review.config': 'Configuration Review',
    'pages.import.review.cost': 'Estimated Cost',
    'pages.import.review.cost_desc': 'Based on your current plan and estimated new contacts',
    'pages.import.review.cost_note': 'Actual cost may vary based on final processing results',
    'pages.import.launch.success': 'Import Job Launched!',
    'pages.import.launch.success_desc': 'Your import job has been queued and will start processing shortly.',
    'pages.import.launch.view_job': 'View Job Status',
    'pages.import.launch.new_import': 'Start New Import',
    'pages.import.launch.launching': 'Launching...',
    'pages.import.launch.launch': 'Launch Import',
    'pages.import.steps.upload': 'Upload & Detect',
    'pages.import.steps.mapping': 'Mapping & Rules',
    'pages.import.steps.review': 'Review & Launch',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.cancel': 'Cancel'
  },
  'it-IT': {
    'pages.import.upload.title': 'Importa Contatti',
    'pages.import.upload.subtitle': 'Carica un file CSV o incolla i dati per importare i contatti',
    'pages.import.upload.drag_drop': 'Trascina e rilascia un file CSV qui',
    'pages.import.upload.drop_here': 'Rilascia il file qui',
    'pages.import.upload.or_click': 'o clicca per sfogliare',
    'pages.import.upload.supported_formats': 'Supporta CSV, XLS, XLSX (max 50MB)',
    'pages.import.paste.label': 'Incolla dati CSV',
    'pages.import.paste.placeholder': 'Incolla i tuoi dati CSV qui (con intestazioni)...',
    'pages.import.paste.processing': 'Elaborazione...',
    'pages.import.paste.process': 'Elabora Dati',
    'pages.import.sheet.title': 'Integrazione Google Sheets',
    'pages.import.sheet.subtitle': 'Prossimamente! Puoi esportare il tuo Google Sheet come CSV e caricarlo qui.',
    'pages.import.sheet.upload_csv': 'Carica CSV Invece',
    'pages.import.processing': 'Elaborazione dei tuoi dati...',
    'pages.import.preview.title': 'Anteprima Dati',
    'pages.import.preview.rows': 'Righe',
    'pages.import.preview.fields': 'Campi',
    'pages.import.preview.delimiter': 'Delimitatore',
    'pages.import.preview.continue': 'Continua al Mapping',
    'pages.import.preview.showing': 'Mostrando le prime 5 righe di',
    'pages.import.preview.total': 'righe totali',
    'pages.import.mapping.title': 'Mapping Campi & Regole',
    'pages.import.mapping.subtitle': 'Mappa le colonne CSV ai campi contatto e configura le regole di import',
    'pages.import.mapping.fields': 'Mapping Campi',
    'pages.import.prefix.title': 'Configurazione Prefisso Numero di Telefono',
    'pages.import.prefix.strategy': 'Strategia Prefisso',
    'pages.import.prefix.auto': 'Rilevamento automatico (+39, 0039, nessuno)',
    'pages.import.prefix.force_39': 'Forza prefisso +39',
    'pages.import.prefix.force_0039': 'Forza prefisso 0039',
    'pages.import.prefix.no_prefix': 'Nessun prefisso (mantieni così)',
    'pages.import.prefix.default_country': 'Paese Predefinito',
    'pages.import.prefix.apply_to_all': 'Applica regole prefisso a tutti i numeri',
    'pages.import.dedupe.title': 'Regole Deduplicazione',
    'pages.import.dedupe.check_on': 'Controlla duplicati su:',
    'pages.import.dedupe.resolve_strategy': 'Quando si trovano duplicati:',
    'pages.import.dedupe.skip': 'Salta duplicati',
    'pages.import.dedupe.merge': 'Unisci e aggiorna esistenti',
    'pages.import.review.title': 'Rivedi & Lancia',
    'pages.import.review.subtitle': 'Rivedi la configurazione di import e lancia il job',
    'pages.import.review.summary': 'Riepilogo Import',
    'pages.import.review.config': 'Rivedi Configurazione',
    'pages.import.review.cost': 'Costo Stimato',
    'pages.import.review.cost_desc': 'Basato sul tuo piano attuale e contatti stimati',
    'pages.import.review.cost_note': 'Il costo effettivo può variare in base ai risultati finali',
    'pages.import.launch.success': 'Job Import Lanciato!',
    'pages.import.launch.success_desc': 'Il tuo job di import è stato accodato e inizierà l\'elaborazione a breve.',
    'pages.import.launch.view_job': 'Visualizza Stato Job',
    'pages.import.launch.new_import': 'Inizia Nuovo Import',
    'pages.import.launch.launching': 'Lancio...',
    'pages.import.launch.launch': 'Lancia Import',
    'pages.import.steps.upload': 'Carica & Rileva',
    'pages.import.steps.mapping': 'Mapping & Regole',
    'pages.import.steps.review': 'Rivedi & Lancia',
    'common.back': 'Indietro',
    'common.next': 'Avanti',
    'common.cancel': 'Annulla'
  }
}

// i18n keys for Billing
export const BILLING_KEYS = {
  'en-US': {
    'billing.payment_methods.add_card': 'Add Payment Method',
    'billing.payment_methods.card_details': 'Card Details',
    'billing.payment_methods.adding': 'Adding...',
    'billing.payment_methods.add': 'Add Card'
  },
  'it-IT': {
    'billing.payment_methods.add_card': 'Aggiungi Metodo di Pagamento',
    'billing.payment_methods.card_details': 'Dettagli Carta',
    'billing.payment_methods.adding': 'Aggiunta...',
    'billing.payment_methods.add': 'Aggiungi Carta'
  }
}


